name: ArtViewer Jobs
on: 
  push:
    branches:
      - main

jobs:
  build:
    name: Building LIVE branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
        path: main
    - uses: actions/setup-node@v1
    - name: "Install dependencies"
      run: |
        cd main
        npm i
    - name: "Build project"
      run: |
        cd main
        npm run build:uimodule
    - uses: actions/checkout@v2
      with:
        ref: live
        path: live
    - name: "Upload project to live branch"
      run: |
        rm -Rf live/*
        cp -R main/uimodule/dist/* live/
        cd live
        git config --global user.name "🤖 GitHub Actions"
        git config --global user.email "beepboop@kuhnchris.eu"
        git add .
        git commit -m 'generated and pushed to live'
        git push
        