name: Art-Convertation Job
on: [push]

jobs:
  ConvertArtJob:
    runs-on: ubuntu-latest
    name: Processing content
    steps:
    - uses: actions/checkout@v2
    - name: Convert Art and create index JSON
      id: convertArt
      uses: kuhnchris/websites-openui5-artviewer@v1
    - name: Commit changes
      uses: EndBug/add-and-commit@v5
      with:
        author_name: 🤖 GitHub-Actions Workflow
        author_email: beepboop@kuhnchris.eu
        message: "Github Action: Converting art"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
